Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,48 +13,51 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.11'
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.11'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-    - name: Run tests
-      run: pytest tests/
+      - name: Run tests
+        run: pytest tests/
 
   deploy:
     runs-on: ubuntu-latest
     needs: build-and-test
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.11'
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.11'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-    - name: Deploy model
-      run: |
-        python deploy.py
+      - name: Deploy model
+        run: |
+          python deploy.py
 
+      - name: Verify deployment directory
+        run: |
+          ls deployment_dir  # List contents of deployment_dir
+          if [ -f "deployment_dir/credit.pkl" ]; then
+            echo "credit.pkl found in deployment_dir."
+          else
+            echo "Error: credit.pkl not found in deployment_dir."
+            exit 1
+          fi
 
-        
-
-
-    - name: Run tests
-      run: |
-        pytest tests/  # Adjust as per your test file structure and location
